conventions.javaMajor = 25

versioning.stage = release

org.gradle.welcome=never
org.gradle.warning.mode=all
org.gradle.logging.stacktrace=all
org.gradle.console=verbose
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=fail

jspecify = 1.0.0
formatj = 0.4.1
clearskies = 0.2.0
pluginPublish = 2.1.1
modPublish = 2.2.0
versioningPlugin = 3.2.0
tokenEnvoy = 1.1.0
foojay = 1.0.0
